--------------------------------------------------------
--  File created - Thursday-May-16-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATCOURSES
--------------------------------------------------------

  CREATE TABLE "TRAININGTRACKING"."CATCOURSES" 
   (	"ID" NUMBER, 
	"IDCATEGORY" NUMBER, 
	"IDCOURSE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATCOURSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAININGTRACKING"."CATCOURSES_PK" ON "TRAININGTRACKING"."CATCOURSES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CATCOURSES
--------------------------------------------------------

  ALTER TABLE "TRAININGTRACKING"."CATCOURSES" ADD CONSTRAINT "CATCOURSES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAININGTRACKING"."CATCOURSES" ADD CONSTRAINT "CATCOURSES_FK1" FOREIGN KEY ("IDCATEGORY") 
  REFERENCES "TRAININGTRACKING"."CATEGORIES" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TRAININGTRACKING"."CATCOURSES" ADD CONSTRAINT "CATCOURSES_FK2" FOREIGN KEY ("IDCOURSE")
  REFERENCES "TRAININGTRACKING"."COURSES" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TRAININGTRACKING"."CATCOURSES" MODIFY ("IDCOURSE" NOT NULL ENABLE);
  ALTER TABLE "TRAININGTRACKING"."CATCOURSES" MODIFY ("IDCATEGORY" NOT NULL ENABLE);
  ALTER TABLE "TRAININGTRACKING"."CATCOURSES" MODIFY ("ID" NOT NULL ENABLE);
