--------------------------------------------------------
--  File created - Tuesday-May-07-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COURSES
--------------------------------------------------------

  CREATE TABLE "TRAININGTRACKING"."COURSES" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"CATEGORY" NUMBER(*,0), 
	"CONTENT" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TRAININGTRACKING.COURSES
SET DEFINE OFF;
Insert into TRAININGTRACKING.COURSES (ID,NAME,DESCRIPTION,CATEGORY,CONTENT) values (10,'A NAME','A DESCRIPTION',1,'A CONTENT');
Insert into TRAININGTRACKING.COURSES (ID,NAME,DESCRIPTION,CATEGORY,CONTENT) values (1,'TEST3',null,1,'SFSDFSF');
--------------------------------------------------------
--  DDL for Index COURSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAININGTRACKING"."COURSES_PK" ON "TRAININGTRACKING"."COURSES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COURSES_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAININGTRACKING"."COURSES_UK1" ON "TRAININGTRACKING"."COURSES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COURSES
--------------------------------------------------------

  ALTER TABLE "TRAININGTRACKING"."COURSES" ADD CONSTRAINT "COURSES_CHK1" CHECK (REGEXP_LIKE(NAME,'^[A-Za-z0-9 ]+$')) ENABLE;
  ALTER TABLE "TRAININGTRACKING"."COURSES" ADD CONSTRAINT "COURSES_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAININGTRACKING"."COURSES" ADD CONSTRAINT "COURSES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRAININGTRACKING"."COURSES" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "TRAININGTRACKING"."COURSES" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "TRAININGTRACKING"."COURSES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAININGTRACKING"."COURSES" MODIFY ("ID" NOT NULL ENABLE);
