-- USER SQL
CREATE USER "trackingsystem" IDENTIFIED BY "internship"  ;

-- QUOTAS

-- ROLES
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "trackingsystem" ;
GRANT "DBA" TO "trackingsystem" ;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "trackingsystem" ;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO "trackingsystem" ;
GRANT "CTXAPP" TO "trackingsystem" ;
GRANT "SELECT_CATALOG_ROLE" TO "trackingsystem" ;
GRANT "CONNECT" TO "trackingsystem" ;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "trackingsystem" ;
GRANT "OEM_MONITOR" TO "trackingsystem" ;
GRANT "APEX_ADMINISTRATOR_ROLE" TO "trackingsystem" ;
GRANT "AQ_USER_ROLE" TO "trackingsystem" ;
GRANT "SCHEDULER_ADMIN" TO "trackingsystem" ;
GRANT "XDB_SET_INVOKER" TO "trackingsystem" ;
GRANT "RECOVERY_CATALOG_OWNER" TO "trackingsystem" ;
GRANT "DBFS_ROLE" TO "trackingsystem" ;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO "trackingsystem" ;
GRANT "HS_ADMIN_SELECT_ROLE" TO "trackingsystem" ;
GRANT "PLUSTRACE" TO "trackingsystem" ;
GRANT "RESOURCE" TO "trackingsystem" ;
GRANT "AQ_ADMINISTRATOR_ROLE" TO "trackingsystem" ;
GRANT "DELETE_CATALOG_ROLE" TO "trackingsystem" ;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO "trackingsystem" ;
GRANT "XDB_WEBSERVICES" TO "trackingsystem" ;
GRANT "EXECUTE_CATALOG_ROLE" TO "trackingsystem" ;
GRANT "EXP_FULL_DATABASE" TO "trackingsystem" ;
GRANT "GATHER_SYSTEM_STATISTICS" TO "trackingsystem" ;
GRANT "LOGSTDBY_ADMINISTRATOR" TO "trackingsystem" ;
GRANT "AUTHENTICATEDUSER" TO "trackingsystem" ;
GRANT "OEM_ADVISOR" TO "trackingsystem" ;
GRANT "HS_ADMIN_ROLE" TO "trackingsystem" ;
GRANT "XDBADMIN" TO "trackingsystem" ;
GRANT "IMP_FULL_DATABASE" TO "trackingsystem" ;
ALTER USER "trackingsystem" DEFAULT ROLE "DATAPUMP_EXP_FULL_DATABASE","DBA","HS_ADMIN_EXECUTE_ROLE","ADM_PARALLEL_EXECUTE_TASK","CTXAPP","SELECT_CATALOG_ROLE","CONNECT","DATAPUMP_IMP_FULL_DATABASE","OEM_MONITOR","APEX_ADMINISTRATOR_ROLE","AQ_USER_ROLE","SCHEDULER_ADMIN","XDB_SET_INVOKER","RECOVERY_CATALOG_OWNER","DBFS_ROLE","XDB_WEBSERVICES_OVER_HTTP","HS_ADMIN_SELECT_ROLE","PLUSTRACE","RESOURCE","AQ_ADMINISTRATOR_ROLE","DELETE_CATALOG_ROLE","XDB_WEBSERVICES_WITH_PUBLIC","XDB_WEBSERVICES","EXECUTE_CATALOG_ROLE","EXP_FULL_DATABASE","GATHER_SYSTEM_STATISTICS","LOGSTDBY_ADMINISTRATOR","AUTHENTICATEDUSER","OEM_ADVISOR","HS_ADMIN_ROLE","XDBADMIN","IMP_FULL_DATABASE";

-- SYSTEM PRIVILEGES

